# Generated by Django 4.2.5 on 2023-10-13 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_question.openquestion'),
        ),
    ]
