# Generated by Django 4.2.5 on 2023-10-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openquestion',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
