# Generated by Django 4.2.5 on 2023-10-16 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_question', '0004_alter_response_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='questions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='open_question.openquestion'),
        ),
    ]
