# Generated by Django 4.2.5 on 2023-10-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_question', '0005_alter_response_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openquestion',
            name='json',
        ),
        migrations.AddField(
            model_name='openquestion',
            name='identifier',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
