# Generated by Django 4.2.5 on 2023-10-18 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_question', '0006_remove_openquestion_json_openquestion_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openquestion',
            name='identifier',
        ),
    ]
